# Generated by Django 3.1.13 on 2021-07-22 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
